# Importing Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder,OneHotEncoder, StandardScaler
from sklearn_extra.cluster import KMedoids
from sklearn.cluster import KMeans, DBSCAN
from scipy.cluster.hierarchy import linkage, dendrogram
from sklearn.metrics import silhouette_score
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import FunctionTransformer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD
from mlxtend.frequent_patterns import apriori, association_rules
from mlxtend.frequent_patterns import fpgrowth

import warnings
warnings.filterwarnings('ignore')

# Importing Dataset

In [2]:
d1 = pd.read_excel('data.xlsx',0)

In [3]:
d1.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [4]:
d2 = pd.read_excel('data.xlsx',1)

In [5]:
d2.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

The following code is used to merge two sheets into one dataset.

In [6]:
data_df = pd.concat([d1,d2])

# EDA

In [7]:
pd.set_option('display.max_rows', None)
data_df.head(100)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom
5,489434,22064,PINK DOUGHNUT TRINKET POT,24,2009-12-01 07:45:00,1.65,13085.0,United Kingdom
6,489434,21871,SAVE THE PLANET MUG,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom
7,489434,21523,FANCY FONT HOME SWEET HOME DOORMAT,10,2009-12-01 07:45:00,5.95,13085.0,United Kingdom
8,489435,22350,CAT BOWL,12,2009-12-01 07:46:00,2.55,13085.0,United Kingdom
9,489435,22349,"DOG BOWL , CHASING BALL DESIGN",12,2009-12-01 07:46:00,3.75,13085.0,United Kingdom
10,489435,22195,HEART MEASURING SPOONS LARGE,24,2009-12-01 07:46:00,1.65,13085.0,United Kingdom
11,489435,22353,LUNCHBOX WITH CUTLERY FAIRY CAKES,12,2009-12-01 07:46:00,2.55,13085.0,United Kingdom
12,489436,48173C,DOOR MAT BLACK FLOCK,10,2009-12-01 09:06:00,5.95,13078.0,United Kingdom
13,489436,21755,LOVE BUILDING BLOCK WORD,18,2009-12-01 09:06:00,5.45,13078.0,United Kingdom
14,489436,21754,HOME BUILDING BLOCK WORD,3,2009-12-01 09:06:00,5.95,13078.0,United Kingdom
15,489436,84879,ASSORTED COLOUR BIRD ORNAMENT,16,2009-12-01 09:06:00,1.69,13078.0,United Kingdom
16,489436,22119,PEACE WOODEN BLOCK LETTERS,3,2009-12-01 09:06:00,6.95,13078.0,United Kingdom
17,489436,22142,CHRISTMAS CRAFT WHITE FAIRY,12,2009-12-01 09:06:00,1.45,13078.0,United Kingdom
18,489436,22296,HEART IVORY TRELLIS LARGE,12,2009-12-01 09:06:00,1.65,13078.0,United Kingdom
19,489436,22295,HEART FILIGREE DOVE LARGE,12,2009-12-01 09:06:00,1.65,13078.0,United Kingdom
20,489436,22109,FULL ENGLISH BREAKFAST PLATE,16,2009-12-01 09:06:00,3.39,13078.0,United Kingdom
21,489436,22107,PIZZA PLATE IN BOX,4,2009-12-01 09:06:00,3.75,13078.0,United Kingdom
22,489436,22194,BLACK DINER WALL CLOCK,2,2009-12-01 09:06:00,8.50,13078.0,United Kingdom
23,489436,35004B,SET OF 3 BLACK FLYING DUCKS,12,2009-12-01 09:06:00,4.65,13078.0,United Kingdom
24,489436,82582,AREA PATROLLED METAL SIGN,12,2009-12-01 09:06:00,2.10,13078.0,United Kingdom
25,489436,21181,PLEASE ONE PERSON METAL SIGN,12,2009-12-01 09:06:00,2.10,13078.0,United Kingdom
26,489436,21756,BATH BUILDING BLOCK WORD,3,2009-12-01 09:06:00,5.95,13078.0,United Kingdom
27,489436,21333,CLASSIC WHITE FRAME,6,2009-12-01 09:06:00,2.95,13078.0,United Kingdom
28,489436,84596F,SMALL MARSHMALLOWS PINK BOWL,8,2009-12-01 09:06:00,1.25,13078.0,United Kingdom
29,489436,84596L,BISCUITS SMALL BOWL LIGHT BLUE,8,2009-12-01 09:06:00,1.25,13078.0,United Kingdom
30,489436,22111,SCOTTIE DOG HOT WATER BOTTLE,24,2009-12-01 09:06:00,4.25,13078.0,United Kingdom
31,489437,22143,CHRISTMAS CRAFT HEART DECORATIONS,6,2009-12-01 09:08:00,2.10,15362.0,United Kingdom
32,489437,22145,CHRISTMAS CRAFT HEART STOCKING,6,2009-12-01 09:08:00,2.10,15362.0,United Kingdom
33,489437,22130,PARTY CONE CHRISTMAS DECORATION,12,2009-12-01 09:08:00,0.85,15362.0,United Kingdom
34,489437,21364,PEACE SMALL WOOD LETTERS,2,2009-12-01 09:08:00,6.75,15362.0,United Kingdom
35,489437,21360,JOY LARGE WOOD LETTERS,1,2009-12-01 09:08:00,9.95,15362.0,United Kingdom
36,489437,21351,CINAMMON & ORANGE WREATH,2,2009-12-01 09:08:00,6.75,15362.0,United Kingdom
37,489437,21352,EUCALYPTUS & PINECONE WREATH,2,2009-12-01 09:08:00,6.75,15362.0,United Kingdom
38,489437,35400,WOODEN BOX ADVENT CALENDAR,2,2009-12-01 09:08:00,8.95,15362.0,United Kingdom
39,489437,20695,FLORAL BLUE MONSTER,3,2009-12-01 09:08:00,4.25,15362.0,United Kingdom
40,489437,37370,RETRO COFFEE MUGS ASSORTED,12,2009-12-01 09:08:00,1.25,15362.0,United Kingdom
41,489437,10002,INFLATABLE POLITICAL GLOBE,12,2009-12-01 09:08:00,0.85,15362.0,United Kingdom
42,489437,84507B,STRIPES DESIGN MONKEY DOLL,6,2009-12-01 09:08:00,2.55,15362.0,United Kingdom
43,489437,20703,BLUE PADDED SOFT MOBILE,3,2009-12-01 09:08:00,4.25,15362.0,United Kingdom
44,489437,21987,PACK OF 6 SKULL PAPER CUPS,12,2009-12-01 09:08:00,0.65,15362.0,United Kingdom
45,489437,21989,PACK OF 20 SKULL PAPER NAPKINS,12,2009-12-01 09:08:00,0.85,15362.0,United Kingdom
46,489437,84970S,HANGING HEART ZINC T-LIGHT HOLDER,12,2009-12-01 09:08:00,0.85,15362.0,United Kingdom
47,489437,20971,PINK BLUE FELT CRAFT TRINKET BOX,12,2009-12-01 09:08:00,1.25,15362.0,United Kingdom
48,489437,22271,FELTCRAFT DOLL ROSIE,6,2009-12-01 09:08:00,2.95,15362.0,United Kingdom
49,489437,22272,FELTCRAFT DOLL MARIA,6,2009-12-01 09:08:00,2.95,15362.0,United Kingdom
50,489437,22274,FELTCRAFT DOLL EMILY,6,2009-12-01 09:08:00,2.95,15362.0,United Kingdom
51,489437,21912,VINTAGE SNAKES & LADDERS,4,2009-12-01 09:08:00,3.75,15362.0,United Kingdom
52,489437,22111,SCOTTIE DOG HOT WATER BOTTLE,3,2009-12-01 09:08:00,4.95,15362.0,United Kingdom
53,489437,22112,CHOCOLATE HOT WATER BOTTLE,3,2009-12-01 09:08:00,4.95,15362.0,United Kingdom
54,489438,21329,DINOSAURS WRITING SET,28,2009-12-01 09:24:00,0.98,18102.0,United Kingdom
55,489438,21252,SET OF MEADOW FLOWER STICKERS,30,2009-12-01 09:24:00,1.69,18102.0,United Kingdom
56,489438,21100,CHARLIE AND LOLA CHARLOTTE BAG,30,2009-12-01 09:24:00,1.15,18102.0,United Kingdom
57,489438,21033,JUMBO BAG CHARLIE AND LOLA TOYS,30,2009-12-01 09:24:00,2.00,18102.0,United Kingdom
58,489438,20711,JUMBO BAG TOYS,60,2009-12-01 09:24:00,1.30,18102.0,United Kingdom
59,489438,21410,COUNTRY COTTAGE DOORSTOP GREEN,32,2009-12-01 09:24:00,2.50,18102.0,United Kingdom
60,489438,21411,GINGHAM HEART DOORSTOP RED,32,2009-12-01 09:24:00,2.50,18102.0,United Kingdom
61,489438,84031A,CHARLIE+LOLA RED HOT WATER BOTTLE,56,2009-12-01 09:24:00,3.00,18102.0,United Kingdom
62,489438,84031B,CHARLIE LOLA BLUE HOT WATER BOTTLE,56,2009-12-01 09:24:00,3.00,18102.0,United Kingdom
63,489438,84032A,CHARLIE+LOLA PINK HOT WATER BOTTLE,60,2009-12-01 09:24:00,1.90,18102.0,United Kingdom
64,489438,84032B,CHARLIE + LOLA RED HOT WATER BOTTLE,56,2009-12-01 09:24:00,1.90,18102.0,United Kingdom
65,489438,84519A,TOMATO CHARLIE+LOLA COASTER SET,56,2009-12-01 09:24:00,2.15,18102.0,United Kingdom
66,489438,84519B,CARROT CHARLIE+LOLA COASTER SET,60,2009-12-01 09:24:00,2.40,18102.0,United Kingdom
67,489438,85132A,CHARLIE + LOLA BISCUITS TINS,60,2009-12-01 09:24:00,6.38,18102.0,United Kingdom
68,489438,85132C,CHARLIE AND LOLA FIGURES TINS,60,2009-12-01 09:24:00,6.40,18102.0,United Kingdom
69,489438,85183A,CHARLIE & LOLA WASTEPAPER BIN BLUE,60,2009-12-01 09:24:00,2.40,18102.0,United Kingdom
70,489438,85183B,CHARLIE & LOLA WASTEPAPER BIN FLORA,60,2009-12-01 09:24:00,2.40,18102.0,United Kingdom
71,489439,22065,CHRISTMAS PUDDING TRINKET POT,12,2009-12-01 09:28:00,1.45,12682.0,France
72,489439,22138,BAKING SET 9 PIECE RETROSPOT,9,2009-12-01 09:28:00,4.95,12682.0,France
73,489439,22139,RETRO SPOT TEA SET CERAMIC 11 PC,9,2009-12-01 09:28:00,4.95,12682.0,France
74,489439,22352,LUNCHBOX WITH CUTLERY RETROSPOT,12,2009-12-01 09:28:00,2.55,12682.0,France
75,489439,85014A,BLACK/BLUE DOTS RUFFLED UMBRELLA,3,2009-12-01 09:28:00,5.95,12682.0,France
76,489439,85014B,RED/WHITE DOTS RUFFLED UMBRELLA,3,2009-12-01 09:28:00,5.95,12682.0,France
77,489439,16161P,WRAP ENGLISH ROSE,25,2009-12-01 09:28:00,0.42,12682.0,France
78,489439,16169N,WRAP BLUE RUSSIAN FOLKART,25,2009-12-01 09:28:00,0.42,12682.0,France
79,489439,21491,SET OF THREE VINTAGE GIFT WRAPS,6,2009-12-01 09:28:00,1.95,12682.0,France
80,489439,22333,RETRO SPORT PARTY BAG + STICKER SET,8,2009-12-01 09:28:00,1.65,12682.0,France
81,489439,85216,ASSORTED CAKES FRIDGE MAGNETS,12,2009-12-01 09:28:00,0.65,12682.0,France
82,489439,21493,VINTAGE DESIGN GIFT TAGS,12,2009-12-01 09:28:00,0.85,12682.0,France
83,489439,22130,PARTY CONE CHRISTMAS DECORATION,24,2009-12-01 09:28:00,0.85,12682.0,France
84,489439,22064,PINK DOUGHNUT TRINKET POT,12,2009-12-01 09:28:00,1.65,12682.0,France
85,489439,21731,RED TOADSTOOL LED NIGHT LIGHT,24,2009-12-01 09:28:00,1.65,12682.0,France
86,489439,85232B,SET/3 RUSSIAN DOLL STACKING TINS,6,2009-12-01 09:28:00,4.95,12682.0,France
87,489439,84691,PACK 20 DOLLY PEGS,12,2009-12-01 09:28:00,0.85,12682.0,France
88,489439,20749,ASSORTED COLOUR MINI CASES,2,2009-12-01 09:28:00,7.95,12682.0,France
89,489439,POST,POSTAGE,3,2009-12-01 09:28:00,18.00,12682.0,France
90,489440,22350,CAT BOWL,8,2009-12-01 09:43:00,2.55,18087.0,United Kingdom
91,489440,22349,"DOG BOWL , CHASING BALL DESIGN",8,2009-12-01 09:43:00,3.75,18087.0,United Kingdom
92,489441,22321,BIRD DECORATION RED SPOT,12,2009-12-01 09:44:00,0.72,18087.0,United Kingdom
93,489441,22138,BAKING SET 9 PIECE RETROSPOT,6,2009-12-01 09:44:00,4.25,18087.0,United Kingdom
94,489441,84029E,RED WOOLLY HOTTIE WHITE HEART.,36,2009-12-01 09:44:00,2.95,18087.0,United Kingdom
95,489441,22111,SCOTTIE DOG HOT WATER BOTTLE,48,2009-12-01 09:44:00,4.25,18087.0,United Kingdom
96,489442,21955,UNION JACK GUNS & ROSES DOORMAT,2,2009-12-01 09:46:00,6.75,13635.0,United Kingdom
97,489442,22111,SCOTTIE DOG HOT WATER BOTTLE,3,2009-12-01 09:46:00,4.95,13635.0,United Kingdom
98,489442,22296,HEART IVORY TRELLIS LARGE,12,2009-12-01 09:46:00,1.65,13635.0,United Kingdom
99,489442,84899E,YELLOW + BROWN BEAR FELT PURSE KIT,12,2009-12-01 09:46:00,1.25,13635.0,United Kingdom

In [8]:
data_df.shape

(1067371, 8)

In [9]:
data_df.describe()

           Quantity         Price    Customer ID
count  1.067371e+06  1.067371e+06  824364.000000
mean   9.938898e+00  4.649388e+00   15324.638504
std    1.727058e+02  1.235531e+02    1697.464450
min   -8.099500e+04 -5.359436e+04   12346.000000
25%    1.000000e+00  1.250000e+00   13975.000000
50%    3.000000e+00  2.100000e+00   15255.000000
75%    1.000000e+01  4.150000e+00   16797.000000
max    8.099500e+04  3.897000e+04   18287.000000

In [10]:
data_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1067371 entries, 0 to 541909
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1067371 non-null  object
 1   StockCode    1067371 non-null  object
 2   Description  1062989 non-null  object
 3   Quantity     1067371 non-null  int64
 4   InvoiceDate  1067371 non-null  datetime64[ns]
 5   Price        1067371 non-null  float64
 6   Customer ID  824364 non-null   float64
 7   Country      1067371 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 73.3+ MB

In [11]:
data_df.isnull().sum()

Invoice             0
StockCode           0
Description      4382
Quantity            0
InvoiceDate         0
Price               0
Customer ID    243007
Country             0
dtype: int64

Missing values are dropped as the dataset is large enough to carryout the required analysis.

In [12]:
data_df.dropna(inplace=True)

In [13]:
data_df.isnull().sum()

Invoice        0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
Price          0
Customer ID    0
Country        0
dtype: int64

As we have a large dataset, the focus will be based on the United Kingdom region as the majority of orders are based on the United Kingdom for a more robust analysis, as well as for the benefit of overtime comparative analysis.

In [14]:
data_df = data_df[data_df['Country'] == 'United Kingdom']

In [15]:
data_df.head(100)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom
5,489434,22064,PINK DOUGHNUT TRINKET POT,24,2009-12-01 07:45:00,1.65,13085.0,United Kingdom
6,489434,21871,SAVE THE PLANET MUG,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom
7,489434,21523,FANCY FONT HOME SWEET HOME DOORMAT,10,2009-12-01 07:45:00,5.95,13085.0,United Kingdom
8,489435,22350,CAT BOWL,12,2009-12-01 07:46:00,2.55,13085.0,United Kingdom
9,489435,22349,"DOG BOWL , CHASING BALL DESIGN",12,2009-12-01 07:46:00,3.75,13085.0,United Kingdom
10,489435,22195,HEART MEASURING SPOONS LARGE,24,2009-12-01 07:46:00,1.65,13085.0,United Kingdom
11,489435,22353,LUNCHBOX WITH CUTLERY FAIRY CAKES,12,2009-12-01 07:46:00,2.55,13085.0,United Kingdom
12,489436,48173C,DOOR MAT BLACK FLOCK,10,2009-12-01 09:06:00,5.95,13078.0,United Kingdom
13,489436,21755,LOVE BUILDING BLOCK WORD,18,2009-12-01 09:06:00,5.45,13078.0,United Kingdom
14,489436,21754,HOME BUILDING BLOCK WORD,3,2009-12-01 09:06:00,5.95,13078.0,United Kingdom
15,489436,84879,ASSORTED COLOUR BIRD ORNAMENT,16,2009-12-01 09:06:00,1.69,13078.0,United Kingdom
16,489436,22119,PEACE WOODEN BLOCK LETTERS,3,2009-12-01 09:06:00,6.95,13078.0,United Kingdom
17,489436,22142,CHRISTMAS CRAFT WHITE FAIRY,12,2009-12-01 09:06:00,1.45,13078.0,United Kingdom
18,489436,22296,HEART IVORY TRELLIS LARGE,12,2009-12-01 09:06:00,1.65,13078.0,United Kingdom
19,489436,22295,HEART FILIGREE DOVE LARGE,12,2009-12-01 09:06:00,1.65,13078.0,United Kingdom
20,489436,22109,FULL ENGLISH BREAKFAST PLATE,16,2009-12-01 09:06:00,3.39,13078.0,United Kingdom
21,489436,22107,PIZZA PLATE IN BOX,4,2009-12-01 09:06:00,3.75,13078.0,United Kingdom
22,489436,22194,BLACK DINER WALL CLOCK,2,2009-12-01 09:06:00,8.50,13078.0,United Kingdom
23,489436,35004B,SET OF 3 BLACK FLYING DUCKS,12,2009-12-01 09:06:00,4.65,13078.0,United Kingdom
24,489436,82582,AREA PATROLLED METAL SIGN,12,2009-12-01 09:06:00,2.10,13078.0,United Kingdom
25,489436,21181,PLEASE ONE PERSON METAL SIGN,12,2009-12-01 09:06:00,2.10,13078.0,United Kingdom
26,489436,21756,BATH BUILDING BLOCK WORD,3,2009-12-01 09:06:00,5.95,13078.0,United Kingdom
27,489436,21333,CLASSIC WHITE FRAME,6,2009-12-01 09:06:00,2.95,13078.0,United Kingdom
28,489436,84596F,SMALL MARSHMALLOWS PINK BOWL,8,2009-12-01 09:06:00,1.25,13078.0,United Kingdom
29,489436,84596L,BISCUITS SMALL BOWL LIGHT BLUE,8,2009-12-01 09:06:00,1.25,13078.0,United Kingdom
30,489436,22111,SCOTTIE DOG HOT WATER BOTTLE,24,2009-12-01 09:06:00,4.25,13078.0,United Kingdom
31,489437,22143,CHRISTMAS CRAFT HEART DECORATIONS,6,2009-12-01 09:08:00,2.10,15362.0,United Kingdom
32,489437,22145,CHRISTMAS CRAFT HEART STOCKING,6,2009-12-01 09:08:00,2.10,15362.0,United Kingdom
33,489437,22130,PARTY CONE CHRISTMAS DECORATION,12,2009-12-01 09:08:00,0.85,15362.0,United Kingdom
34,489437,21364,PEACE SMALL WOOD LETTERS,2,2009-12-01 09:08:00,6.75,15362.0,United Kingdom
35,489437,21360,JOY LARGE WOOD LETTERS,1,2009-12-01 09:08:00,9.95,15362.0,United Kingdom
36,489437,21351,CINAMMON & ORANGE WREATH,2,2009-12-01 09:08:00,6.75,15362.0,United Kingdom
37,489437,21352,EUCALYPTUS & PINECONE WREATH,2,2009-12-01 09:08:00,6.75,15362.0,United Kingdom
38,489437,35400,WOODEN BOX ADVENT CALENDAR,2,2009-12-01 09:08:00,8.95,15362.0,United Kingdom
39,489437,20695,FLORAL BLUE MONSTER,3,2009-12-01 09:08:00,4.25,15362.0,United Kingdom
40,489437,37370,RETRO COFFEE MUGS ASSORTED,12,2009-12-01 09:08:00,1.25,15362.0,United Kingdom
41,489437,10002,INFLATABLE POLITICAL GLOBE,12,2009-12-01 09:08:00,0.85,15362.0,United Kingdom
42,489437,84507B,STRIPES DESIGN MONKEY DOLL,6,2009-12-01 09:08:00,2.55,15362.0,United Kingdom
43,489437,20703,BLUE PADDED SOFT MOBILE,3,2009-12-01 09:08:00,4.25,15362.0,United Kingdom
44,489437,21987,PACK OF 6 SKULL PAPER CUPS,12,2009-12-01 09:08:00,0.65,15362.0,United Kingdom
45,489437,21989,PACK OF 20 SKULL PAPER NAPKINS,12,2009-12-01 09:08:00,0.85,15362.0,United Kingdom
46,489437,84970S,HANGING HEART ZINC T-LIGHT HOLDER,12,2009-12-01 09:08:00,0.85,15362.0,United Kingdom
47,489437,20971,PINK BLUE FELT CRAFT TRINKET BOX,12,2009-12-01 09:08:00,1.25,15362.0,United Kingdom
48,489437,22271,FELTCRAFT DOLL ROSIE,6,2009-12-01 09:08:00,2.95,15362.0,United Kingdom
49,489437,22272,FELTCRAFT DOLL MARIA,6,2009-12-01 09:08:00,2.95,15362.0,United Kingdom
50,489437,22274,FELTCRAFT DOLL EMILY,6,2009-12-01 09:08:00,2.95,15362.0,United Kingdom
51,489437,21912,VINTAGE SNAKES & LADDERS,4,2009-12-01 09:08:00,3.75,15362.0,United Kingdom
52,489437,22111,SCOTTIE DOG HOT WATER BOTTLE,3,2009-12-01 09:08:00,4.95,15362.0,United Kingdom
53,489437,22112,CHOCOLATE HOT WATER BOTTLE,3,2009-12-01 09:08:00,4.95,15362.0,United Kingdom
54,489438,21329,DINOSAURS WRITING SET,28,2009-12-01 09:24:00,0.98,18102.0,United Kingdom
55,489438,21252,SET OF MEADOW FLOWER STICKERS,30,2009-12-01 09:24:00,1.69,18102.0,United Kingdom
56,489438,21100,CHARLIE AND LOLA CHARLOTTE BAG,30,2009-12-01 09:24:00,1.15,18102.0,United Kingdom
57,489438,21033,JUMBO BAG CHARLIE AND LOLA TOYS,30,2009-12-01 09:24:00,2.00,18102.0,United Kingdom
58,489438,20711,JUMBO BAG TOYS,60,2009-12-01 09:24:00,1.30,18102.0,United Kingdom
59,489438,21410,COUNTRY COTTAGE DOORSTOP GREEN,32,2009-12-01 09:24:00,2.50,18102.0,United Kingdom
60,489438,21411,GINGHAM HEART DOORSTOP RED,32,2009-12-01 09:24:00,2.50,18102.0,United Kingdom
61,489438,84031A,CHARLIE+LOLA RED HOT WATER BOTTLE,56,2009-12-01 09:24:00,3.00,18102.0,United Kingdom
62,489438,84031B,CHARLIE LOLA BLUE HOT WATER BOTTLE,56,2009-12-01 09:24:00,3.00,18102.0,United Kingdom
63,489438,84032A,CHARLIE+LOLA PINK HOT WATER BOTTLE,60,2009-12-01 09:24:00,1.90,18102.0,United Kingdom
64,489438,84032B,CHARLIE + LOLA RED HOT WATER BOTTLE,56,2009-12-01 09:24:00,1.90,18102.0,United Kingdom
65,489438,84519A,TOMATO CHARLIE+LOLA COASTER SET,56,2009-12-01 09:24:00,2.15,18102.0,United Kingdom
66,489438,84519B,CARROT CHARLIE+LOLA COASTER SET,60,2009-12-01 09:24:00,2.40,18102.0,United Kingdom
67,489438,85132A,CHARLIE + LOLA BISCUITS TINS,60,2009-12-01 09:24:00,6.38,18102.0,United Kingdom
68,489438,85132C,CHARLIE AND LOLA FIGURES TINS,60,2009-12-01 09:24:00,6.40,18102.0,United Kingdom
69,489438,85183A,CHARLIE & LOLA WASTEPAPER BIN BLUE,60,2009-12-01 09:24:00,2.40,18102.0,United Kingdom
70,489438,85183B,CHARLIE & LOLA WASTEPAPER BIN FLORA,60,2009-12-01 09:24:00,2.40,18102.0,United Kingdom
90,489440,22350,CAT BOWL,8,2009-12-01 09:43:00,2.55,18087.0,United Kingdom
91,489440,22349,"DOG BOWL , CHASING BALL DESIGN",8,2009-12-01 09:43:00,3.75,18087.0,United Kingdom
92,489441,22321,BIRD DECORATION RED SPOT,12,2009-12-01 09:44:00,0.72,18087.0,United Kingdom
93,489441,22138,BAKING SET 9 PIECE RETROSPOT,6,2009-12-01 09:44:00,4.25,18087.0,United Kingdom
94,489441,84029E,RED WOOLLY HOTTIE WHITE HEART.,36,2009-12-01 09:44:00,2.95,18087.0,United Kingdom
95,489441,22111,SCOTTIE DOG HOT WATER BOTTLE,48,2009-12-01 09:44:00,4.25,18087.0,United Kingdom
96,489442,21955,UNION JACK GUNS & ROSES DOORMAT,2,2009-12-01 09:46:00,6.75,13635.0,United Kingdom
97,489442,22111,SCOTTIE DOG HOT WATER BOTTLE,3,2009-12-01 09:46:00,4.95,13635.0,United Kingdom
98,489442,22296,HEART IVORY TRELLIS LARGE,12,2009-12-01 09:46:00,1.65,13635.0,United Kingdom
99,489442,84899E,YELLOW + BROWN BEAR FELT PURSE KIT,12,2009-12-01 09:46:00,1.25,13635.0,United Kingdom
100,489442,22271,FELTCRAFT DOLL ROSIE,6,2009-12-01 09:46:00,2.95,13635.0,United Kingdom
101,489442,22272,FELTCRAFT DOLL MARIA,6,2009-12-01 09:46:00,2.95,13635.0,United Kingdom
102,489442,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2009-12-01 09:46:00,2.95,13635.0,United Kingdom
103,489442,21582,KINGS CHOICE SMALL TUBE MATCHES,20,2009-12-01 09:46:00,1.65,13635.0,United Kingdom
104,489442,21586,KINGS CHOICE GIANT TUBE MATCHES,12,2009-12-01 09:46:00,2.55,13635.0,United Kingdom
105,489442,21590,KINGS CHOICE CIGAR BOX MATCHES,48,2009-12-01 09:46:00,1.25,13635.0,United Kingdom
106,489442,22091,EMPIRE TISSUE BOX,12,2009-12-01 09:46:00,1.25,13635.0,United Kingdom
107,489442,84251J,"GREETING CARD, THE BLACK CAT",12,2009-12-01 09:46:00,0.42,13635.0,United Kingdom
108,489442,22024,RAINY LADIES BIRTHDAY CARD,12,2009-12-01 09:46:00,0.42,13635.0,United Kingdom
109,489442,22026,BANQUET BIRTHDAY CARD,12,2009-12-01 09:46:00,0.42,13635.0,United Kingdom
110,489442,22029,SPACE BOY BIRTHDAY CARD,12,2009-12-01 09:46:00,0.42,13635.0,United Kingdom
111,489442,22025,RING OF ROSES BIRTHDAY CARD,12,2009-12-01 09:46:00,0.42,13635.0,United Kingdom
112,489442,22031,BOTANICAL LAVENDER BIRTHDAY CARD,12,2009-12-01 09:46:00,0.42,13635.0,United Kingdom
113,489442,21428,SET3 BOOK BOX GREEN GINGHAM FLOWER,4,2009-12-01 09:46:00,4.25,13635.0,United Kingdom
114,489442,21430,SET/3 RED GINGHAM ROSE STORAGE BOX,4,2009-12-01 09:46:00,3.75,13635.0,United Kingdom
115,489442,21916,SET 12 RETRO WHITE CHALK STICKS,24,2009-12-01 09:46:00,0.42,13635.0,United Kingdom
116,489442,21790,VINTAGE SNAP CARDS,12,2009-12-01 09:46:00,0.85,13635.0,United Kingdom
117,489442,21888,BINGO SET,8,2009-12-01 09:46:00,3.75,13635.0,United Kingdom
118,489442,85178,VICTORIAN SEWING KIT,12,2009-12-01 09:46:00,1.25,13635.0,United Kingdom

In [16]:
data_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 741301 entries, 0 to 541893
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      741301 non-null  object
 1   StockCode    741301 non-null  object
 2   Description  741301 non-null  object
 3   Quantity     741301 non-null  int64
 4   InvoiceDate  741301 non-null  datetime64[ns]
 5   Price        741301 non-null  float64
 6   Customer ID  741301 non-null  float64
 7   Country      741301 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 50.9+ MB

In [17]:
data_df.shape

(741301, 8)

In [18]:
for col in data_df.columns:
    print(col, data_df[col].unique())

Invoice [489434 489435 489436 ... 581584 581585 581586]
StockCode [85048 '79323P' '79323W' ... 23562 23561 23843]
Description ['15CM CHRISTMAS GLASS BALL 20 LIGHTS' 'PINK CHERRY LIGHTS'
 ' WHITE CHERRY LIGHTS' ... 'SILVER AND BLACK ORBIT NECKLACE'
 'CREAM HANGING HEART T-LIGHT HOLDER' 'PAPER CRAFT , LITTLE BIRDIE']
Quantity [    12     48     24     10     18      3     16      4      2      6
      8      1     28     30     60     32     56     36     20     -3
     -2    576    288     27     64    160     -6      5     -1     72
     50      7     25    800    -12      9     11     -4     58    192
     96    144    100    180    216     15    240    108     33     90
     81    -24    -81    -48     17     -5     -8     -9     13     21
    120    200    168     19    280    128     40     80    300    450
     14     61     46    504     45    480   4320   5184   4008     22
    600    505    500     23     47    432    252     75   -504   -600
   -252   -246    -36    360    107     49     42     66    -10     34
     52    400     70    936    -32    -60    -18    -96    -50    -16
   -120     35    -64   -168    256   1500    320    130   1002     26
   1080     -7     29    -23    -13     67     54    960    864    150
    126    468    336   3000    -25     38    208    334    124    125
    117     39    -20     55    -11     78   -100    -17   -144     77
    350    526     98    112     59     37    408   1440    832     43
     65    720    271     41    264    225    104    163    187    312
    204    224    164    110   -190    250    -72    284     89    118
    -30    -14     44    -44    132   -132    -27    229     62     82
    114   -150    -26    156    -22    460     84   -300    374    190
    484    384    -21     51    -40    900   1800     53   -192   -240
    -15    152    700     74   1008   -432   1200   -108    141    537
    140    -28    -80     31    205    247    372   2016     87     68
     91    148   1000    640  10000    -74    135     76    840    816
    324    -42    648     85   -200   1152    102   -408    -38  -1440
    -34    498   -288   -204   -160    176    246     71    516    270
   -309    392    -19    396    612    322   -400   -500   -280   -140
   -128   -250   -156    105    175    136    171  -1200    -69   -312
    -51    -49   5000   2500     88    808   2664   1728    624    228
   2972   1098   1128    276    -41    134    830   -830    210   -210
    730    122   3500    -98    -99   1056    220    352    -29    -61
   2000   -576   -320   -648    248    198    330   -720     95    -85
    235    -90    174    -55   2304   1120    985     63    327   -180
   -118     97    121    394   1920   7128   3960    560    876    756
    672   -324    189    768   2004    608   1512    444   3936   2976
   4752   1872   1116    567    684    984   1308   2112   2952   4992
   2496   3648   1536   1248   1632   7008   3072   3744   4608   1104
    704    760    464    520    139    -35    -31    162    304    -59
   3120   1224   2880   -700    196    201    402    625   1240  -1152
   -384    888    -56   -148   1944   1960   9360   6336   -270    169
    243   -243   2400    213    212  -2400   1680   -248   -256   1584
   -212   -213     57   -110    -82    -68    -45    -37    -65   -129
   -117    -33  -9360   1824     69   1400    378    972   1394    272
    -47   1296    147    860   1010   1356   1284    186   1930   3114
   1300    670  74215 -74215    456    -94   2592    420    -76   3906
   -102   2160    342    -46    151    -58   -670  -1300  -1930  -2000
  -3114    462    492    273   -960   1350    428  -1350    101    227
   2700    222    906    552    738   4300    -52   1600    323   1515
  -1515    660   -420    188    588   -480   -164    430    701    828
    540    696    512    291   3186     83     79   -360    -75    109
   -121    129    261    348   1900    157    -39    116    968    824
   -828   -701    410    236    230   -334   -318   -126   -113     86
     93    494   1788    744    416    496    306   1878    666    708
   1428    852   1412    528   -756   -152    -79    -43    183   -186
    -53    -70   1540   -130   -220   -840  -1296    255   -468     92
   4800    -66   -112   1992    232    992    630   1020   2100   -162
    -67   -276   -184    234    244   -244   -234  12540    115    774
    490    388    620   1404    698  80995 -80995]
InvoiceDate ['2009-12-01T07:45:00.000000000' '2009-12-01T07:46:00.000000000'
 '2009-12-01T09:06:00.000000000' ... '2011-12-09T12:25:00.000000000'
 '2011-12-09T12:31:00.000000000' '2011-12-09T12:49:00.000000000']
Price [6.950000e+00 6.750000e+00 2.100000e+00 1.250000e+00 1.650000e+00
 5.950000e+00 2.550000e+00 3.750000e+00 5.450000e+00 1.690000e+00
 1.450000e+00 3.390000e+00 8.500000e+00 4.650000e+00 2.950000e+00
 4.250000e+00 8.500000e-01 9.950000e+00 8.950000e+00 6.500000e-01
 4.950000e+00 9.800000e-01 1.150000e+00 2.000000e+00 1.300000e+00
 2.500000e+00 3.000000e+00 1.900000e+00 2.150000e+00 2.400000e+00
 6.380000e+00 6.400000e+00 7.200000e-01 4.200000e-01 5.500000e-01
 3.800000e-01 1.275000e+01 1.950000e+00 3.950000e+00 2.120000e+00
 6.350000e+00 2.100000e-01 7.950000e+00 1.490000e+00 1.495000e+01
 3.450000e+00 1.060000e+00 2.750000e+00 1.095000e+01 5.490000e+00
 1.695000e+01 3.250000e+00 9.500000e-01 2.900000e-01 9.000000e+00
 1.900000e+01 2.250000e+00 1.995000e+01 9.580000e+00 3.400000e-01
 1.900000e-01 6.400000e-01 3.490000e+00 3.700000e-01 1.000000e-01
 4.595000e+01 1.895000e+01 2.995000e+01 2.195000e+01 1.075000e+01
 1.550000e+00 1.065000e+01 1.050000e+00 1.400000e-01 5.100000e+00
 8.490000e+00 1.850000e+00 4.600000e+00 3.810000e+00 3.350000e+00
 1.595000e+01 1.750000e+00 3.600000e-01 1.800000e-01 3.495000e+01
 1.200000e-01 7.650000e+00 0.000000e+00 7.500000e+00 5.550000e+00
 8.000000e-02 6.000000e-02 5.000000e-01 7.995000e+01 1.475000e+01
 2.500000e-01 1.195000e+01 4.800000e-01 3.200000e-01 6.700000e-01
 2.990000e+00 1.500000e+00 1.998490e+03 3.500000e+00 2.200000e-01
 1.600000e-01 3.995000e+01 7.250000e+00 7.350000e+00 4.995000e+01
 4.000000e-02 3.097300e+02 1.000000e+01 4.000000e+00 1.500000e+01
 5.000000e+01 8.700000e+00 7.900000e-01 5.750000e+00 9.450000e+00
 1.270000e+00 4.000000e+01 1.213020e+03 2.200000e+00 6.450000e+00
 9.100000e+00 9.000000e-02 4.500000e+00 6.090000e+00 2.360000e+00
 1.400000e+00 3.595000e+01 5.000000e+00 5.900000e-01 1.190000e+00
 3.200000e+00 2.600000e+00 1.000000e+00 1.700000e+00 2.495000e+01
 3.500000e-01 2.200000e+01 6.850000e+00 5.400000e+00 8.460000e+00
 5.473000e+02 7.410000e+01 6.896000e+01 3.380000e+00 7.930000e+00
 7.300000e+00 6.437000e+01 7.060000e+00 7.360000e+00 1.760000e+01
 1.700000e-01 6.000000e+00 7.000000e-01 2.800000e+00 8.000000e+00
 1.100000e+00 7.000000e+00 5.850000e+00 4.410000e+00 8.400000e-01
 2.000000e+01 4.000000e-01 1.300000e-01 1.000000e-03 7.000000e+01
 6.250000e+00 3.000000e-01 5.300000e-01 6.360000e+00 1.050000e+01
 1.400000e+01 1.314000e+01 2.619000e+01 3.428000e+02 1.783100e+02
 1.558000e+01 1.049000e+01 1.257800e+02 1.838000e+01 1.312000e+01
 4.935000e+01 1.051000e+01 1.633000e+01 1.574000e+01 4.896000e+01
 2.363000e+01 2.185000e+01 2.436300e+02 1.148900e+02 1.576000e+01
 8.161000e+01 1.035000e+02 3.875400e+02 1.988000e+01 2.850000e+01
 2.460000e+01 8.985600e+03 1.065540e+03 5.501000e+01 2.447700e+02
 2.595000e+01 1.300000e+01 7.490000e+00 4.800000e+00 2.560000e+00
 1.028400e+02 8.970000e+00 2.350000e+00 4.112000e+01 1.000000e+02
 2.695000e+01 4.495000e+01 8.220000e+00 2.140000e+00 2.700000e+00
 6.200000e+01 4.580000e+00 7.000000e-02 5.995000e+01 6.000000e+01
 7.500000e-01 6.960000e+00 7.260000e+00 8.800000e-01 1.250000e+02
 6.300000e-01 2.400000e-01 1.100000e-01 3.087400e+02 6.995000e+01
 1.200000e+00 2.300000e+00 2.000000e-01 7.320000e+00 5.250000e+00
 1.800000e+00 1.295000e+01 2.413800e+02 7.630000e+00 5.065100e+02
 1.348600e+02 3.226900e+02 2.746300e+02 4.500000e-01 5.800000e-01
 1.095350e+04 1.144730e+03 7.793200e+02 2.900000e+00 1.899670e+03
 1.598670e+03 5.256500e+02 1.834140e+03 3.023100e+02 1.817000e+01
 2.317000e+01 3.590000e+00 4.317000e+01 1.180000e+00 1.920000e+00
 2.660000e+00 1.980000e+00 1.380000e+00 3.620000e+00 1.740000e+00
 8.000000e-01 6.000000e-01 3.670000e+00 5.880000e+00 6.680000e+00
 1.289000e+01 2.562000e+01 3.761700e+02 6.410000e+00 8.960000e+00
 3.300000e-01 1.590000e+00 7.980000e+00 1.066000e+01 6.770000e+00
 8.620000e+00 5.360000e+00 5.843700e+03 7.735000e+02 2.104700e+02
 2.451260e+03 2.272800e+02 3.066600e+02 1.486900e+02 9.480000e+01
 5.763000e+01 4.217590e+03 4.750000e+00 5.876340e+03 2.290000e+00
 3.740000e+00 3.660000e+00 7.450000e+00 1.935000e+01 1.831000e+01
 3.000000e+01 2.164500e+02 6.075300e+02 4.800000e+01 1.100000e+02
 5.200000e-01 1.580000e+00 7.940000e+00 1.480000e+00 1.099000e+01
 5.261000e+01 6.600000e-01 3.001300e+02 7.245000e+01 3.584700e+02
 7.970000e+00 1.019900e+02 4.770000e+00 5.929000e+01 5.690000e+01
 2.362000e+01 8.070000e+01 3.510000e+01 7.460000e+00 4.860000e+00
 8.700000e-01 5.430000e+00 1.470000e+00 2.975700e+02 8.494500e+02
 6.480500e+02 1.000630e+03 5.900000e+02 8.516000e+02 3.552000e+02
 9.550600e+02 3.248860e+03 4.620860e+03 2.511109e+04 3.020900e+02
 4.170000e+00 1.655000e+01 3.660000e+01 8.210000e+00 1.800000e+01
 5.180000e+00 1.294000e+01 4.660000e+00 2.588000e+01 1.322000e+01
 3.178000e+01 1.423100e+02 1.842000e+01 2.030000e+01 6.200000e-01
 2.500000e+01 1.588510e+03 1.510000e+00 2.950000e+02 3.580800e+03
 7.800000e-01 2.700000e-01 1.080000e+00 5.060000e+00 3.180000e+00
 2.540000e+00 1.570000e+00 8.850000e+01 9.500000e+01 1.420000e+02
 9.380000e+00 3.610500e+03 2.400000e+01 2.980000e+00 8.000000e+02
 4.797000e+01 3.348800e+02 8.920000e+00 4.100000e-01 3.016600e+02
 6.725000e+01 1.330000e+00 4.960000e+00 1.660000e+00 6.860000e+00
 1.500000e+02 4.100000e+00 1.970000e+00 3.860000e+00 6.760000e+00
 8.900000e-01 2.470000e+00 1.000000e-02 1.235000e+01 6.775000e+02
 5.914300e+02 1.200000e+01 4.450500e+02 1.920000e+01 9.900000e+00
 9.090000e+00 4.400000e-01 1.030000e+01 1.046880e+04 2.769900e+03
 2.809100e+02 4.295000e+01 1.299500e+02 1.770000e+00 6.844000e+01
 2.294600e+02 2.245800e+02 6.698000e+01 1.276600e+02 4.500000e+01
 7.445400e+02 8.415000e+01 9.888000e+01 7.161000e+01 1.343440e+03
 1.595400e+02 3.597100e+02 2.086300e+02 3.100000e-01 5.000000e-02
 3.000000e-02 4.560000e+00 5.150000e+00 4.140000e+00 8.870000e+00
 6.890000e+00 1.430000e+00 5.960000e+00 3.170000e+00 7.130000e+00
 3.400000e+00 1.880000e+00 6.540000e+00 2.852000e+01 9.000000e-01
 1.720000e+00 3.980000e+00 4.450600e+02 7.044790e+03 2.285310e+03
 1.216000e+01 1.950000e+01 1.769600e+02 3.119900e+02 2.670500e+02
 9.680000e+00 1.130000e+01 7.564000e+02 1.108440e+03 2.667880e+03
 3.880000e+00 1.686000e+01 4.780000e+00 5.370000e+00 9.860000e+00
 6.780000e+00 1.942000e+01 9.890000e+00 2.320000e+00 1.688000e+01
 5.278000e+01 3.506000e+02 3.450100e+02 2.225170e+03 1.408000e+01
 1.259600e+02 1.586500e+02 5.303100e+02 8.301200e+02 6.938000e+01
 1.085000e+01 2.650000e+00 6.199200e+02 8.800000e+00 1.010000e+01
 1.650000e+02 1.450000e+02 3.240000e+00 6.910000e+00 2.170000e+00
 4.620000e+00 2.690000e+00 9.160000e+00 6.600000e+00 3.210000e+00
 2.210000e+00 2.160000e+00 7.300000e-01 1.240000e+00 3.440000e+00
 4.680000e+00 1.013000e+01 1.435000e+01 5.740000e+00 1.389000e+01
 9.203000e+01 7.831000e+01 8.200000e+00 1.008000e+01 5.005000e+01
 3.269000e+01 1.984000e+01 2.319000e+01 1.600000e+01 2.310000e+00
 9.260000e+00 6.210000e+01 4.900000e-01 1.269510e+03 1.075200e+02
 1.902000e+01 3.904000e+01 3.603000e+01 2.395000e+01 6.500000e+01
 3.960000e+00 1.170000e+00 1.630000e+01 1.398000e+01 1.186000e+01
 6.130000e+00 7.840000e+00 5.670000e+00 3.200000e+01 3.229000e+01
 2.840000e+00 1.420000e+00 1.870000e+00 2.750000e+01 3.820000e+00
 3.370000e+00 3.575000e+01 2.929000e+01 3.500000e+01 1.930000e+00
 2.810000e+02 5.277000e+01 2.671200e+02 1.994000e+01 1.750000e+02
 5.760000e+00 4.250000e+01 2.693000e+01 1.234000e+01 1.530000e+00
 9.400000e-01 1.388000e+01 2.297000e+01 5.720000e+00 6.700000e+00
 2.655000e+02 2.220000e+00 1.299000e+01 1.040000e+00 5.795000e+01
 2.080000e+00 4.150000e+00 7.146000e+01 6.427000e+01 6.591000e+01
 8.564800e+02 8.480000e+01 1.908000e+02 7.001000e+01 2.081600e+02
 3.900000e-01 8.250000e+01 8.200000e-01 8.150000e+00 3.019000e+01
 8.300000e-01 7.900000e+00 6.980000e+00 3.038000e+01 8.500000e+01
 2.890000e+00 8.250000e+00 1.950000e+02 3.295000e+01 8.650000e+00
 9.870000e+00 4.400000e+00 9.100000e-01 6.800000e-01 1.298000e+01
 3.850000e+00 1.622400e+02 5.700000e+00 7.880000e+00 5.760000e+01
 1.452000e+01 7.600000e-01 1.790000e+00 6.650000e+00 1.867860e+03
 3.088200e+02 1.505000e+01 1.250000e+01 2.490000e+00 1.582100e+02
 3.290000e+00 7.050000e+00 2.178000e+01 1.040000e+01 1.200000e+02
 3.150000e+00 1.176000e+01 1.010000e+00 4.000000e+02 1.115000e+01
 8.142750e+03 6.930000e+03 1.184000e+01 3.347100e+02 5.390000e+00
 6.900000e-01 9.299000e+02 9.150000e+00 2.330000e+00 7.620000e+00
 3.320000e+00 9.420000e+00 6.790000e+00 2.960000e+00 1.163000e+01
 6.420000e+00 4.270000e+00 2.460000e+00 1.680000e+00 9.840000e+00
 1.596000e+01 3.710000e+00 4.175000e+01 6.500000e+00 7.500000e+01
 4.180000e+00 1.170000e+01 4.200000e+01 1.248000e+01 2.092000e+01
 1.293800e+02 2.804000e+01 6.000000e+02 4.050000e+00 6.495000e+02
 3.897000e+04 2.020000e+00 3.910000e+00 3.900000e+00 1.299000e+02
 1.442000e+01 2.800000e-01 8.600000e-01 2.260000e+00 2.620000e+00
 5.800000e+00 5.455800e+02 7.850000e+00 4.370000e+00 3.560000e+00
 5.320000e+00 1.760000e+00 4.900000e+00 3.520000e+00 2.880000e+00
 9.360000e+00 1.399000e+01 2.390000e+00 4.287630e+03 5.506400e+02
 7.172300e+02 1.592490e+03 6.118600e+02 2.949200e+02 7.054500e+02
 1.123500e+02 1.064000e+02 4.514200e+02 3.060600e+03 1.215000e+01
 6.624000e+01 4.300000e+00 4.560000e+01 3.650000e+01 2.605000e+01
 9.600000e+00 1.020000e+00 2.500000e+02 4.363000e+01 3.155950e+03
 1.034000e+01 2.083400e+02 6.400000e+01 2.500000e+03 3.280000e+00
 4.020000e+00 4.080000e+00 5.140000e+00 5.080000e+00 1.152000e+01
 1.630000e+00 1.230000e+00 1.117000e+01 1.600000e+00 1.667000e+01
 1.507000e+01 1.006000e+01 8.740000e+01 7.968000e+01 6.617000e+01
 3.375000e+01 1.320000e+00 3.630000e+01 3.839000e+01 2.000000e+02
 1.450000e+01 8.528000e+02 5.790000e+00 8.290000e+00 4.130000e+00
 1.079000e+01 1.646000e+01 1.301000e+01 1.104300e+02 1.310000e+00
 7.080000e+00 4.533000e+01 1.104500e+02 1.316000e+01 1.246000e+01
 2.075000e+01 2.496000e+01 5.224000e+01 1.579000e+01 1.413000e+01
 8.558000e+01 1.022400e+02 1.829840e+03 2.033100e+03 3.450300e+02
 2.410000e+00 6.086600e+02 8.785500e+02 6.630000e+00 1.663000e+01
 2.920000e+00 9.960000e+00 8.120000e+00 1.640000e+00 5.640000e+00
 6.720000e+00 1.960000e+00 9.980000e+00 4.670000e+00 1.167000e+01
 1.862000e+01 3.120000e+00 1.496000e+01 2.913000e+01 1.329000e+01
 3.329000e+01 6.880800e+02 4.475600e+02 8.000000e+01 9.000000e+01
 9.130000e+00 4.902500e+02 3.615900e+02 3.260000e+00 1.120000e+00
 6.670000e+00 2.850000e+00 4.980000e+00 5.660000e+00 3.580000e+00
 5.350000e+00 3.570000e+00 3.890000e+00 3.970000e+00 5.680000e+00
 1.527800e+02 3.222000e+01 1.674000e+01 1.607000e+01 2.187200e+02
 6.820500e+02 1.996000e+01 1.460000e+00 4.119200e+02 6.350100e+02
 7.436200e+02 4.959800e+02 7.920000e+01 1.205800e+02 1.665000e+01
 2.080000e+01 3.920000e+00 4.649000e+02 4.251400e+02 6.383000e+02
 1.455000e+01 3.130000e+00 1.670000e+00 2.327000e+01 9.070000e+02
 1.710000e+00 9.015800e+02 6.060000e+02 5.500000e+00 1.039000e+01
 3.970000e+01 1.159000e+01 6.411000e+01 2.480000e+00 1.110000e+00
 9.081600e+02 5.175100e+02 9.714000e+01 5.170000e+00 2.670000e+00
 7.400000e-01 9.200000e-01 1.830000e+02 1.038750e+03 1.500360e+03
 8.505000e+02 2.100000e+01 2.726000e+01 1.488000e+01 1.982000e+01
 1.676000e+01 6.710000e+00 2.040000e+00 5.600000e-01 1.270060e+03
 8.499300e+02 7.600000e+00 1.526760e+03 9.871400e+02 5.130000e+00
 9.720000e+00 2.050000e+01 2.053000e+01 2.868000e+01 2.420000e+00
 3.160000e+00 4.700000e+00 2.195000e+02 1.100440e+03 1.599260e+03
 1.860000e+00 3.300000e+00 1.335000e+01 4.760000e+00 2.246900e+02]
Customer ID [13085. 13078. 15362. ... 13436. 15520. 13298.]

Country ['United Kingdom']

As the dataset is large, it is sampled randomly to smaller size to be able to carry out the required analysis, as the computer is unable or takes too long to process the dataset.

In [19]:
sample_data = 30000  
random_data_df = data_df.sample(n=sample_data, random_state=42)

In [20]:
random_data_df.shape

(30000, 8)

To understand the dataset and the uniqueness of each feature, the following code is used on all coumns.

In [21]:
random_data_df['Description'].nunique()

3787

In [22]:
random_data_df['Description'].nunique()

3787

In [23]:
random_data_df['Invoice'].nunique()

16282

In [24]:
random_data_df['StockCode'].nunique()

3485

In [25]:
random_data_df['Quantity'].nunique()

158

In [26]:
random_data_df['InvoiceDate'].nunique()

15819

In [27]:
random_data_df['Price'].nunique()

235

In [28]:
random_data_df['Customer ID'].nunique()

4077

In [29]:
random_data_df['Country'].nunique()

1

# Encoding Features

The following code is used to capture time based patterns in the data, which might be relevant for both clustering and market basket analysis.

In [34]:
columns_encode = ["Invoice", "StockCode", "Description", "Country"]
random_data_df[columns_encode] = random_data_df[columns_encode].astype(str)

one_hot_encoder = OneHotEncoder(sparse=False, handle_unknown='ignore')  
encoded_data = one_hot_encoder.fit_transform(random_data_df[columns_encode])

In [35]:
encoded_columns = pd.DataFrame(encoded_data, columns=one_hot_encoder.get_feature_names_out(columns_encode))

In [40]:
random_data_df.reset_index(drop=True, inplace=True)
encoded_columns.reset_index(drop=True, inplace=True)

In [41]:
random_data_df_encoded = pd.concat([random_data_df, encoded_columns], axis=1)

In [42]:
random_data_df_encoded.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Invoice_489434,Invoice_489436,...,Description_ZINC SWEETHEART SOAP DISH,Description_ZINC SWEETHEART WIRE LETTER RACK,Description_ZINC T-LIGHT HOLDER STAR LARGE,Description_ZINC T-LIGHT HOLDER STARS LARGE,Description_ZINC T-LIGHT HOLDER STARS SMALL,Description_ZINC TOP 2 DOOR WOODEN SHELF,Description_ZINC WILLIE WINKIE CANDLE STICK,Description_ZINC WIRE KITCHEN ORGANISER,Description_ZINC WIRE SWEETHEART LETTER TRAY,Country_United Kingdom
0,558355,84927F,PSYCHEDELIC TILE HOOK,2,2011-06-28 14:58:00,2.10,13614.0,United Kingdom,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,533114,22175,PINK OWL SOFT TOY,1,2010-11-16 12:22:00,2.95,14675.0,United Kingdom,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,514985,21671,RED SPOT CERAMIC DRAWER KNOB,1,2010-07-07 13:55:00,1.25,15494.0,United Kingdom,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,561679,85099B,JUMBO BAG RED RETROSPOT,10,2011-07-28 18:56:00,2.08,15245.0,United Kingdom,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,572912,22362,GLASS JAR PEACOCK BATH SALTS,2,2011-10-26 16:07:00,2.95,16915.0,United Kingdom,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [30]:
random_data_df['InvoiceDate'] = pd.to_datetime(random_data_df['InvoiceDate'])
random_data_df['InvoiceYear'] = random_data_df['InvoiceDate'].dt.year
random_data_df['InvoiceMonth'] = random_data_df['InvoiceDate'].dt.month
random_data_df['InvoiceDay'] = random_data_df['InvoiceDate'].dt.day
random_data_df['InvoiceHour'] = random_data_df['InvoiceDate'].dt.hour
random_data_df['InvoiceMinute'] = random_data_df['InvoiceDate'].dt.minute

In [33]:
data_df = pd.get_dummies(random_data_df, columns=['InvoiceYear', 'InvoiceMonth', 'InvoiceDay', 'InvoiceHour', 'InvoiceMinute'])

In [35]:
label_encoder = LabelEncoder()
for col in ['Invoice', 'StockCode', 'Description', 'Country']:
    if data_df[col].dtype == 'object':
        data_df[col] = label_encoder.fit_transform(data_df[col])

TypeError: Encoders require their input argument must be uniformly strings or numbers. Got ['int', 'str']

In [ ]:
#random_data_df['InvoiceDate'] = pd.to_datetime(random_data_df['InvoiceDate'])

def extract_date_features(random_data_df):
    random_data_df['Year'] = random_data_df['InvoiceDate'].dt.year
    random_data_df['Month'] = random_data_df['InvoiceDate'].dt.month
    random_data_df['Day'] = random_data_df['InvoiceDate'].dt.day
    random_data_df['Hour'] = random_data_df['InvoiceDate'].dt.hour
    random_data_df['Day of Week'] = random_data_df['InvoiceDate'].dt.dayofweek
    return random_data_df[['Year', 'Month', 'Day', 'Hour', 'Day of Week']]

For accurate analysis results, One Hot Encoder is used as it ensures that categorical data is properly represented without introducing any ordinality bias.

In [ ]:
date_transformer = Pipeline(steps=[
    ('extract', FunctionTransformer(extract_date_features)),
    ('encoder', OneHotEncoder(handle_unknown='ignore', sparse=False))
])

date_columns = ['InvoiceDate']
preprocessor = ColumnTransformer(
    transformers=[
        ('date', date_transformer, date_columns)
    ],
    remainder='passthrough'
)

In [ ]:
preprocessor = ColumnTransformer(
    transformers=[
        ('date', date_transformer, ['InvoiceDate']),
        # Add other transformations for non-date columns if needed
    ],
    remainder='passthrough'
)

In [ ]:
transformed_data = preprocessor.fit_transform(random_data_df)
transformed_data_df = pd.DataFrame(transformed_data, columns=preprocessor.get_feature_names_out())

In [ ]:
random_data_df.head()

In [ ]:
random_data_df.info()

In [ ]:
',

In [ ]:
ffdgsegdsgs

In [ ]:
numeric_features = ['Quantity', 'Price']
numeric_transformer = StandardScaler()

In [ ]:
categorical_features = ['Country']
categorical_transformer = OneHotEncoder(handle_unknown='ignore')

In [ ]:
text_features = ['Description']
text_transformer = Pipeline(steps=[
    ('tfidf', TfidfVectorizer()),
    ('svd', TruncatedSVD(n_components=50))  # Dimensionality reduction
])

In [ ]:
from sklearn.compose import ColumnTransformer

In [ ]:
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features),
        # ('text', text_transformer, text_features),
        ('date', date_transformer, ['InvoiceDate'])
])

In [ ]:
# Prepare full pipeline (without KMeans to determine the best number of clusters)
pipeline = Pipeline(steps=[('preprocessor', preprocessor)])

In [ ]:
# Process the data
processed_data = pipeline.fit_transform(random_sample)

In [ ]:
# Elbow method to determine the best number of clusters
wcss = []
for i in range(1, 11):  # Test 1 to 10 clusters
    kmeans = KMeans(n_clusters=i, init='k-means++', max_iter=300, n_init=10, random_state=0)
    kmeans.fit(processed_data)
    wcss.append(kmeans.inertia_)

In [ ]:
# Plotting the results onto a line graph to observe 'The Elbow'
plt.figure(figsize=(10, 8))
plt.plot(range(1, 11), wcss)
plt.title('The Elbow Method')
plt.xlabel('Number of clusters')
plt.ylabel('WCSS')  # Within cluster sum of squares
plt.show()

In [ ]:
## Based on the Elbow method, the best number of clusters is 4
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features),
        # ('text', text_transformer, text_features),
        ('date', date_transformer, ['InvoiceDate'])
    ])

In [ ]:
# Clustering pipeline
clf = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('cluster', KMeans(n_clusters=4))
])

In [ ]:
# Fit model
clf.fit(random_sample)

In [ ]:
# Predict clusters
clusters = clf.predict(random_sample)

In [ ]:
# Add clusters back to the original DataFrame
random_sample['Cluster'] = clusters

In [ ]:
random_sample.head()

In [ ]:
from sklearn.decomposition import PCA

In [ ]:
clf.fit(random_sample)

In [ ]:
X_transformed = clf.named_steps['preprocessor'].transform(random_sample)

In [ ]:
svd = TruncatedSVD(n_components=2)
X_svd = svd.fit_transform(X_transformed)

In [ ]:
labels = clf.named_steps['cluster'].labels_

In [ ]:
plt.scatter(X_svd[:, 0], X_svd[:, 1], c=labels, cmap='viridis')
plt.xlabel('Component 1')
plt.ylabel('Component 2')
plt.title('KMeans Clustering')
plt.colorbar(label='Cluster')
plt.show()

In [ ]:
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_transformed)

In [ ]:
labels = clf.named_steps['cluster'].labels_

In [ ]:
plt.scatter(X_pca[:, 0], X_pca[:, 1], c=labels, cmap='viridis')
plt.xlabel('PC1')
plt.ylabel('PC2')
plt.title('KMeans Clustering')
plt.colorbar(label='Cluster')
plt.show()

In [ ]:
selected_features = ['Quantity', 'Price', 'Customer ID']
new_data = random_sample[selected_features]

In [ ]:
scaler = StandardScaler()
data_scaled = scaler.fit_transform(new_data)

In [ ]:
kmeans = KMeans(n_clusters=2, random_state=42)
kmeans_clusters = kmeans.fit_predict(data_scaled)

In [ ]:
wcss = []
for k in range(1,10):
    kmeans = KMeans(n_clusters=k, n_init=10, random_state=42)
    kmeans.fit(data_scaled)
    wcss.append(kmeans.inertia_)
print(wcss)

In [ ]:
plt.plot(range(1,10), wcss);

In [ ]:
kmeans_silhouette = silhouette_score(data_scaled, kmeans_clusters)
print("Silhouette Score for KMeans:", kmeans_silhouette)

In [ ]:
from sklearn.cluster import DBSCAN
from sklearn_extra.cluster import KMedoids

In [ ]:
dbscan = DBSCAN(eps=0.5, min_samples=5)
dbscan_clusters = dbscan.fit_predict(data_scaled)

In [ ]:
dbscan_silhouette = silhouette_score(data_scaled, dbscan_clusters)
print("Silhouette Score for DBSCAN:", dbscan_silhouette)

In [ ]:
kmedoids = KMedoids(n_clusters=5, random_state=42)
kmedoids_clusters = kmedoids.fit_predict(data_scaled)

In [ ]:
kmedoids_silhouette = silhouette_score(data_scaled, kmedoids_clusters)
print("Silhouette Score for K-Medoids:", kmedoids_silhouette)

In [ ]:
from sklearn.decomposition import PCA

In [ ]:
clf.fit(data_df)

In [ ]:
gdgrstrs

In [ ]:
data_encoded = pd.get_dummies(random_sample, columns=['Country', 'Description'])

In [ ]:
data_encoded['StockCode'].dtype

In [ ]:
data_encoded['StockCode'] = data_encoded['StockCode'].str.extract('(\d+)')

In [ ]:
missing_values = data_encoded.isna().sum()
print(missing_values)

In [ ]:
data_encoded.head()

In [ ]:
scaler = StandardScaler()
data_scaled = scaler.fit_transform(data_encoded)

In [ ]:
scaler = StandardScaler()
data_scaled = scaler.fit_transform(data_encoded[['Quantity', 'Customer ID', 'Price']])

In [ ]:
kmeans = KMeans(n_clusters=5, random_state=42)

In [ ]:
kmeans_clusters = kmeans.fit_predict(data_scaled)

In [ ]:
wcss = []
for k in range(2, 10):
    kmeans = KMeans(n_clusters=k, n_init=10, random_state=42)
    kmeans.fit(data_scaled)
    wcss.append(kmeans.inertia_)
print(wcss)

In [ ]:
plt.plot(range(2,10), wcss);

In [ ]:
kmeans_silhouette = silhouette_score(data_scaled, kmeans_clusters)
print("Silhouette Score for KMeans:", kmeans_silhouette)

In [ ]:
plt.scatter(data_scaled[:, 0], data_scaled[:, 1], c=kmeans_clusters, cmap='viridis', s=50, edgecolors='k')
plt.title('KMeans Clustering')
plt.xlabel('Feature 1')
plt.ylabel('Feature 2')
plt.show()

In [ ]:
plt.figure(figsize=(12, 6))
plt.subplot(1, 3, 1)
plt.scatter(data_scaled[:, 0], data_scaled[:, 1], c=kmeans_clusters, cmap='viridis')
plt.title(f'K-Means (Silhouette Score: {kmeans_silhouette:.2f})')
plt.xlabel('Quantity (Scaled)')
plt.ylabel('Price (Scaled)')
plt.tight_layout()
plt.show()

In [ ]:
from sklearn.cluster import DBSCAN

In [ ]:
dbscan = DBSCAN(eps=0.5, min_samples=5)
dbscan_clusters = dbscan.fit_predict(data_scaled)

In [ ]:
plt.subplot(1, 3, 2)
plt.scatter(data_scaled[:, 0], data_scaled[:, 1], c=dbscan_clusters, cmap='viridis')
plt.title('DBSCAN')
plt.xlabel('Quantity (Scaled)')
plt.ylabel('Price (Scaled)')
plt.tight_layout()
plt.show()

In [ ]:
dfvdfd

In [ ]:
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.cluster import KMeans, DBSCAN, AgglomerativeClustering

In [ ]:
data_encoded = pd.get_dummies(data_df, columns=['Country', 'Description'])

In [ ]:
scaler = StandardScaler()
data_scaled = scaler.fit_transform(data_encoded[['Quantity', 'Price']])

In [ ]:
data_scaled

In [ ]:
wcss = []
for k in range(2, 10):
    kmeans = KMeans(n_clusters=k, n_init=10, random_state=42)
    kmeans.fit(data_scaled)
    wcss.append(kmeans.inertia_)
print(wcss)

In [ ]:
plt.plot(range(2,10), wcss);

In [ ]:
kmeans = KMeans(n_clusters=3, n_init=10, random_state=42)

In [ ]:
data_scaled.head()

In [ ]:
kmeans.cluster_centers_

In [ ]:
kmeans.fit(data_scaled)

kmeans_silhouette = silhouette_score(data_scaled, kmeans_clusters)

In [ ]:
plt.figure(figsize=(12, 6))
plt.subplot(1, 3, 1)
plt.scatter(data_scaled[:, 0], data_scaled[:, 1], c=kmeans_clusters, cmap='viridis')
plt.title(f'K-Means (Silhouette Score: {kmeans_silhouette:.2f})')
plt.xlabel('Quantity (Scaled)')
plt.ylabel('Price (Scaled)')
plt.tight_layout()
plt.show()

Label encoder to be used to transform Country from a categorical feature into a numerical feature to be able to use it in clustering.

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
label = LabelEncoder()

In [ ]:
data_df['New Country']=label.fit_transform(data_df['Country'])

In [ ]:
data_df.drop(['Country'],axis=1,inplace=True)

In [ ]:
data_df.head(100)

Drop categorical data and create a new dataset that consists of three features that will be clustered.

In [ ]:
new_data = data_df[['Quantity', 'Price', 'New Country']]

In [ ]:
plt.figure(figsize=(12, 6))
plt.subplot(1, 2, 1)
sns.histplot(data=new_data, x='Quantity', bins=20, kde=True)
plt.title('Distribution of Quantity')

plt.subplot(1, 2, 2)
sns.histplot(data=new_data, x='Price', bins=20, kde=True)
plt.title('Distribution of Price')

plt.tight_layout()
plt.show()

In [ ]:
plt.figure(figsize=(8, 6))
sns.scatterplot(data=new_data, x='Quantity', y='Price')
plt.title('Scatter Plot of Quantity vs. Price')
plt.xlabel('Quantity')
plt.ylabel('Price')
plt.show()

In [ ]:
plt.figure(figsize=(10, 6))
sns.boxplot(data=new_data[['Quantity', 'Price']])
plt.title('Box Plot of Quantity and Price')
plt.ylabel('Value')
plt.show()

In [ ]:
plt.figure(figsize=(12, 6))
sns.countplot(data=new_data, x='New Country', order=new_data['New Country'].value_counts().index)
plt.title('Bar Plot of New Country')
plt.xticks(rotation=45)
plt.xlabel('Country')
plt.ylabel('Count')
plt.show()

In [ ]:
plt.figure(figsize=(12, 6))
sns.violinplot(data=new_data, x='New Country', y='Quantity')
plt.title('Violin Plot of Quantity by New Country')
plt.xticks(rotation=45)
plt.xlabel('Country')
plt.ylabel('Quantity')
plt.show()

sns.kdeplot(new_df['New Country'], shade=True,hue=new_data['Quantity']);

for i in columns:
    plt.figure()
    sns.displot(columns[i])

Using standard scaler to improve the performance of algorithms.

In [ ]:
scaler = StandardScaler()
scaled = scaler.fit_transform(new_data)

In [ ]:
new_data.head()

In [ ]:
clustering1 = KMeans(n_clusters=2)

In [ ]:
clustering1.fit(new_data[['New Country']])

In [ ]:
clustering1.labels_

In [ ]:
new_data['Country Cluster']=clustering1.labels_
new_data.head()

In [ ]:
new_data['Country Cluster'].value_counts()

In [ ]:
clustering1.inertia_

In [ ]:
wcss = []
for k in range(1, 10):
    kmeans = KMeans(n_clusters=k, n_init=10, random_state=42)
    kmeans.fit(new_data[['New Country']])
    wcss.append(kmeans.inertia_)
print(wcss)

In [ ]:
plt.plot(range(1,10), wcss);

In [ ]:
new_data.groupby('Country Cluster')['Quantity', 
       'Price', 'New Country'].mean()

In [ ]:
clustering2 = KMeans(n_clusters=3)
clustering2.fit(new_data[['New Country','Quantity']])
new_data['Country Cluster and Quantity'] = clustering2.labels_
new_data.head()

In [ ]:
wcss1 = []
for k in range(1, 10):
    kmeans1 = KMeans(n_clusters=k, n_init=10, random_state=42)
    kmeans1.fit(new_data[['New Country','Quantity']])
    wcss1.append(kmeans1.inertia_)
print(wcss1)

In [ ]:
plt.plot(range(1,10), wcss1);

In [ ]:
sns.scatterplot(data=new_data, x='New Country', y='Quantity',hue='Country Cluster and Quantity')

In [ ]:
center = pd.DataFrame(clustering2.cluster_centers_)
center.columns = ['X', 'Y']

In [ ]:
plt.figure(figsize=(10,8))
plt.scatter(x=center['X'],y=center['Y'],s=100,c='black',marker='*')

sns.scatterplot(data=new_data, x='New Country', y='Quantity',hue='Country Cluster and Quantity')

In [ ]:
kmeans = KMeans(n_clusters=6, n_init=10, random_state=42)
kmeans.fit_predict('Quantity')

In [ ]:
wcss = []
for k in range(0, 10):
    kmeans = KMeans(n_clusters=k, n_init=10, random_state=42)
    kmeans.fit(new_data)
    wcss.append(kmeans.inertia_)
print(wcss)

In [ ]:
plt.plot(range(2,10), wcss);

In [ ]:
new_data['Country Cluster'] = kmeans.labels_
new_data.head(100)

In [ ]:
def plotFeatures(col1, col2):
    plt.scatter(
        new_data[kmeans.labels_ == 0].iloc[:, col1],
        new_data[kmeans.labels_ == 0].iloc[:, col2],
        s=50,
        c='red',
        label='Cluster 1'
    )
    plt.scatter(
        new_data[kmeans.labels_ == 1].iloc[:, col1],
        new_data[kmeans.labels_ == 1].iloc[:, col2],
        s=50,
        c='blue',
        label='Cluster 2'
    )
    plt.scatter(
        new_data[kmeans.labels_ == 2].iloc[:, col1],
        new_data[kmeans.labels_ == 2].iloc[:, col2],
        s=50,
        c='green',
        label='Cluster 3'
    )
    plt.scatter(
        kmeans.cluster_centers_[:, col1],
        kmeans.cluster_centers_[:, col2],
        s=100,
        c='yellow',
        label='Centroids'
    )
    plt.xlabel(new_data.columns[col1])
    plt.ylabel(new_data.columns[col2])
    plt.legend()
    plt.title('Clustering based on ' + new_data.columns[col1] + ' and ' + new_data.columns[col2])
    plt.show()

plotFeatures(0, 1)

In [ ]:
plotFeatures(0,2)

In [ ]:
plotFeatures(1,2)

kmeans = KMeans(n_clusters=3,n_init=10,random_state=42)

y_pred = kmeans.fit_predict(x)

y_pred

wcss = []
for k in range(2,10):
    kmeans = KMeans(n_clusters=k,n_init=10,random_state=42)
    kmeans.fit(x)
    wcss.append(kmeans.inertia_)
print(wcss)

plt.plot(range(2,10),wcss);

silhouette_score(x,y_pred)

In [ ]:
clustering1 = KMeans()

In [ ]:
clustering1.fit(new_data[['New Country']])

In [ ]:
clustering1.labels_
#for label in clustering1.labels_:
    #print(label)

In [ ]:
new_data['Country Cluster'].value_counts()

In [ ]:
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn_extra.cluster import KMedoids

In [ ]:
df = data_df[['Quantity','Price']]

In [ ]:
df.head()

In [ ]:
standard = StandardScaler()

In [ ]:
x = standard.fit_transform(df)

In [ ]:
coumns = df.columns

In [ ]:
coumns

In [ ]:
df = pd.DataFrame(standard.fit_transform(df),columns=coumns)

In [ ]:
df.head()

K-elbow method

In [ ]:
wcss = []
for k in range (2,10):
    kmeans = KMeans(n_clusters = k,random_state=42)
    kmeans.fit(x)
    wcss.append(kmeans.inertia_)
plt.plot(range(2,10),wcss);

Silhouette Score

wcss = []
for k in range (2,10):
    kmeans = KMeans(n_clusters = k,random_state=42)
    y_kmeans = kmeans.fit_predict(df)
    wcss.append(silhouette_score(df,y_kmeans))
plt.plot(range(2,10),wcss);